//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Hospital_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int doc_id { get; set; }
        public string doc_name { get; set; }
        public string doc_email { get; set; }
        public string doc_phone { get; set; }
        public string doc_password { get; set; }
    }
}
